on: pull_request

env:
  # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
  Timezone: UTC
  # Set this to the output folder for all of the generated files. Unless you have a very
  # good reason to change this you should leave it as KiBotOutput.
  OutputFolder: KiriOutput
  Project: ${{ github.event.repository.name }}

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install dependencies
        run: |
          # Installing dependencies
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_dependencies.sh)"

      - name: Install Kiri
        run: |
          # Installing KiRI and Kicad Plugin
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_kiri.sh)"

      - name: Run Kiri
        run: |
          eval $(opam env)
          export TK_SILENCE_DEPRECATION=1
          export PATH=${HOME}/.local/share/kiri/submodules/KiCad-Diff/:PATH
          export PATH=${HOME}/.local/share/kiri/bin:PATH
          
          kiri ${{ env.Project }}.kicad_pro -d ${{ env.OutputFolder }} -l
      
      - name: Upload Kiri diff
        if: ${{ failure() }}
        uses: edunad/actions-image@v1.0.1
        with:
            path: ${{ env.OutputFolder }}/*.svg
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: 'Kiri diff'
      
      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ${{ env.OutputFolder }}
          path: ${{ env.OutputFolder }}/**