on: pull_request

env:
  # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
  Timezone: UTC
  # Set this to the output folder for all of the generated files. Unless you have a very
  # good reason to change this you should leave it as KiBotOutput.
  OutputFolder: KiBotOutput
  Project: ${{ github.event.repository.name }}

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Kiri
        run: |
          # Installing dependencies
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_dependencies.sh)"
          # Installing KiRI and Kicad Plugin
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_kiri.sh)"

      - name: Run Kiri
        run: |
          kiri -l ${{ env.Project }}.kicad_pro
      
      - name: Upload Kirir diff
        if: ${{ failure() }}
        uses: edunad/actions-image@v1.0.1
        with:
            path: '*.svg'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: 'Failed E2E tests 🙀'